import { useCallback, useEffect, useMemo, useState } from 'react'
import {
  BookOpen, Building2, CalendarDays, ChevronDown, CircleDollarSign, ClipboardList,
  Download, FileBarChart, FileSpreadsheet, FolderCog, Landmark, LayoutDashboard,
  LogOut, Menu, PenLine, Plus, ReceiptText, RefreshCw, Send, Settings, ShieldCheck,
  Upload, UserCog, Users as UsersIcon, WalletCards, X, CheckCircle2, AlertTriangle, ArrowUpRight,
  FileText, RotateCcw, LockKeyhole
} from 'lucide-react'
import { BarChart, Bar, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import * as XLSX from 'xlsx'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { download, request } from './api.js'

const today = () => new Date().toISOString().slice(0, 10)
const firstDay = () => `${today().slice(0, 8)}01`
const rupiah = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 })
const money = (value) => rupiah.format(Number(value || 0))
const number = (value) => new Intl.NumberFormat('id-ID', { maximumFractionDigits: 2 }).format(Number(value || 0))
const dateLabel = (value) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(new Date(`${String(value).slice(0, 10)}T00:00:00`)) : '—'
const apiPath = (path, values = {}) => `${path}?${new URLSearchParams(Object.entries(values).filter(([, value]) => value !== '' && value !== undefined && value !== null)).toString()}`

const nav = [
  ['dashboard', 'Dashboard', LayoutDashboard], ['journals', 'Jurnal', ReceiptText], ['imports', 'Impor Excel', Upload],
  ['reports', 'Laporan', FileBarChart], ['accounts', 'Chart of Accounts', BookOpen], ['periods', 'Periode', CalendarDays],
  ['users', 'Pengguna', UsersIcon], ['settings', 'Pengaturan', Settings]
]

function useLoad(loader, deps = []) {
  const [state, setState] = useState({ loading: true, data: null, error: '' })
  const reload = useCallback(async () => {
    setState((current) => ({ ...current, loading: true, error: '' }))
    try { setState({ loading: false, data: await loader(), error: '' }) }
    catch (error) { setState({ loading: false, data: null, error: error.message }) }
  }, deps) // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { reload() }, [reload])
  return { ...state, reload }
}

function PageLoading() { return <div className="loading"><div><div className="spinner" /><div>Memuat data…</div></div></div> }
function Empty({ children = 'Belum ada data untuk ditampilkan.' }) { return <div className="empty"><FileText /><div>{children}</div></div> }
function Badge({ status }) {
  const value = String(status || '').toUpperCase()
  const classes = value === 'POSTED' || value === 'OPEN' || value === 'ADMIN' ? 'green' : value === 'DRAFT' ? 'amber' : value === 'CLOSED' || value === 'VOID' ? 'slate' : 'red'
  const text = ({ POSTED: 'Terposting', DRAFT: 'Draft', OPEN: 'Terbuka', CLOSED: 'Terkunci', ADMIN: 'Admin', STAFF: 'Staf' })[value] || status
  return <span className={`badge ${classes}`}>{text}</span>
}
function Button({ children, variant = 'primary', small = false, ...props }) { return <button className={`button ${variant} ${small ? 'small' : ''}`} {...props}>{children}</button> }
function Modal({ title, children, onClose, footer }) { return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose}><X /></button></div><div className="modal-body">{children}</div>{footer && <div className="modal-foot">{footer}</div>}</div></div> }
function ErrorNotice({ error }) { return error ? <div className="error-box"><AlertTriangle size={16} style={{ verticalAlign: 'middle', marginRight: 6 }} />{error}</div> : null }

function Login({ onLogin }) {
  const [email, setEmail] = useState('admin@finova.local')
  const [password, setPassword] = useState('Admin123!')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  async function submit(event) {
    event.preventDefault(); setBusy(true); setError('')
    try { onLogin((await request('/auth/login', { method: 'POST', body: { email, password } })).user) }
    catch (reason) { setError(reason.message) } finally { setBusy(false) }
  }
  return <div className="login-page">
    <section className="login-aside"><div><div className="brand" style={{ padding: 0 }}><span className="brand-mark"><Landmark /></span>Finova</div><h1>Keuangan rapi, keputusan lebih pasti.</h1><p>Sistem akuntansi perusahaan yang mengubah setiap transaksi menjadi laporan keuangan siap baca.</p><div className="feature-list"><div className="feature"><CheckCircle2 /> Jurnal berpasangan dan periode terkunci</div><div className="feature"><CheckCircle2 /> Impor Excel dengan validasi otomatis</div><div className="feature"><CheckCircle2 /> Laporan real-time dan siap diekspor</div></div></div><small>FINOVA · SISTEM AKUNTANSI INDONESIA</small></section>
    <main className="login-form-wrap"><form className="login-card" onSubmit={submit}><div className="brand" style={{ padding: 0, color: '#0b5a39' }}><span className="brand-mark"><Landmark /></span>Finova</div><h2>Selamat datang</h2><p>Masuk untuk melanjutkan pencatatan keuangan perusahaan Anda.</p><div className="login-form"><div className="field"><label>EMAIL</label><input className="input" value={email} onChange={(e) => setEmail(e.target.value)} type="email" required /></div><div className="field"><label>KATA SANDI</label><input className="input" value={password} onChange={(e) => setPassword(e.target.value)} type="password" required /></div><ErrorNotice error={error} /><Button disabled={busy}>{busy ? 'Memproses…' : <><LogOut /> Masuk ke Finova</>}</Button></div><div className="demo-note"><strong>Akun awal:</strong><br />admin@finova.local / Admin123!<br />Ubah lewat variabel lingkungan sebelum dipakai di produksi.</div></form></main>
  </div>
}

function AppShell({ user, company, route, setRoute, onLogout, children }) {
  const item = nav.find(([key]) => key === route) || nav[0]
  const menus = nav.filter(([key]) => user.role === 'ADMIN' || !['imports', 'accounts', 'periods', 'users', 'settings'].includes(key))
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Landmark /></span>Finova</div><div className="company-label">{company?.name || 'Perusahaan Anda'}</div><div className="nav-list">{menus.map(([key, label, Icon]) => <button key={key} className={`nav-item ${route === key ? 'active' : ''}`} onClick={() => setRoute(key)}><Icon /><span>{label}</span></button>)}</div><div className="sidebar-bottom">Pembukuan lebih tenang.<br />Data tersimpan dengan jejak audit.</div></aside>
    <main className="main"><header className="topbar"><div className="breadcrumb">Sistem Akuntansi<strong>{item[1]}</strong></div><div className="profile-chip"><div className="avatar">{user.name.slice(0, 1).toUpperCase()}</div><div><div className="profile-name">{user.name}</div><div className="profile-role">{user.role === 'ADMIN' ? 'Administrator' : 'Staf Keuangan'}</div></div><button className="icon-button" title="Keluar" onClick={onLogout}><LogOut size={16} /></button></div></header><div className="content">{children}</div><nav className="mobile-nav">{menus.slice(0, 5).map(([key, label, Icon]) => <button key={key} className={`nav-item ${route === key ? 'active' : ''}`} title={label} onClick={() => setRoute(key)}><Icon /><span>{label}</span></button>)}</nav></main>
  </div>
}

function Dashboard() {
  const [range, setRange] = useState({ from: firstDay(), to: today() })
  const { data, loading, error, reload } = useLoad(() => request(apiPath('/reports/dashboard', range)), [range.from, range.to])
  if (loading) return <PageLoading />
  const values = data?.data
  const stats = values ? [['Kas & Bank', values.cashBank, WalletCards], ['Piutang', values.receivables, ArrowUpRight], ['Utang Usaha', values.payables, ReceiptText], ['Pendapatan', values.revenue, CircleDollarSign], ['Laba Bersih', values.netIncome, Landmark]] : []
  const chart = values ? [{ name: 'Pendapatan', value: values.revenue }, { name: 'Beban', value: values.expenses }, { name: 'Laba', value: values.netIncome }] : []
  return <><div className="toolbar"><div><h1 className="page-title">Ringkasan keuangan</h1><p className="page-copy">Pantau posisi dan kinerja perusahaan dalam satu tempat.</p></div><div className="filter-row"><div className="field"><label>DARI</label><input className="input" type="date" value={range.from} onChange={(e) => setRange({ ...range, from: e.target.value })} /></div><div className="field"><label>SAMPAI</label><input className="input" type="date" value={range.to} onChange={(e) => setRange({ ...range, to: e.target.value })} /></div><Button variant="secondary" small onClick={reload}><RefreshCw /> Segarkan</Button></div></div><ErrorNotice error={error} />
    <div className="stats">{stats.map(([label, value, Icon]) => <article className="stat-card" key={label}><div className="stat-label">{label}</div><div className={`stat-value ${label === 'Laba Bersih' && value < 0 ? 'bad' : ''}`}>{money(value)}</div><div className="stat-icon"><Icon /></div></article>)}</div>
    {values && <div className="grid-two"><section className="panel"><h3 className="panel-title">Kinerja periode ini</h3><p className="panel-subtitle">Perbandingan pendapatan, beban, dan laba bersih.</p><div style={{ height: 270 }}><ResponsiveContainer><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis tickFormatter={(value) => `${Math.round(value / 1000000)} jt`} tickLine={false} axisLine={false} /><Tooltip formatter={(value) => money(value)} /><Bar dataKey="value" fill="#168b55" radius={[7, 7, 0, 0]} /></BarChart></ResponsiveContainer></div></section><section className="panel"><h3 className="panel-title">Perhatian akuntansi</h3><p className="panel-subtitle">Kontrol sederhana untuk pembukuan yang sehat.</p><div className="report-line"><span>Periode aktif</span><strong>{dateLabel(range.from)} — {dateLabel(range.to)}</strong></div><div className="report-line"><span>Status pembukuan</span><Badge status="OPEN" /></div><div className="report-line"><span>Saldo kas dan bank</span><strong>{money(values.cashBank)}</strong></div><div className="report-line"><span>Posisi laba</span><strong className={values.netIncome < 0 ? 'bad' : 'good'}>{values.netIncome >= 0 ? 'Surplus' : 'Defisit'}</strong></div><div className="report-line total"><span>Total beban</span><strong>{money(values.expenses)}</strong></div></section></div>}
  </>
}

function JournalModal({ accounts, entry, onClose, onSaved, notify }) {
  const [form, setForm] = useState(() => ({ voucherNo: entry?.voucher_no || '', entryDate: entry?.entry_date?.slice(0, 10) || today(), description: entry?.description || '', lines: entry?.lines?.map((line) => ({ account_id: String(line.account_id), debit: line.debit || '', credit: line.credit || '', memo: line.memo || '' })) || [{ account_id: '', debit: '', credit: '', memo: '' }, { account_id: '', debit: '', credit: '', memo: '' }] }))
  const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const totals = useMemo(() => ({ debit: form.lines.reduce((sum, line) => sum + Number(line.debit || 0), 0), credit: form.lines.reduce((sum, line) => sum + Number(line.credit || 0), 0) }), [form.lines])
  function changeLine(index, field, value) { const lines = [...form.lines]; lines[index] = { ...lines[index], [field]: value }; if (field === 'debit' && Number(value) > 0) lines[index].credit = ''; if (field === 'credit' && Number(value) > 0) lines[index].debit = ''; setForm({ ...form, lines }) }
  async function save(target) {
    setBusy(true); setError('')
    const body = { ...form, lines: form.lines.map((line) => ({ ...line, account_id: Number(line.account_id), debit: Number(line.debit || 0), credit: Number(line.credit || 0) })) }
    try {
      if (entry) { await request(`/journals/${entry.id}`, { method: 'PUT', body }); if (target === 'POSTED') await request(`/journals/${entry.id}/post`, { method: 'POST' }) }
      else await request('/journals', { method: 'POST', body: { ...body, status: target } })
      notify(target === 'POSTED' ? 'Jurnal berhasil diposting.' : 'Draft jurnal berhasil disimpan.'); onSaved()
    } catch (reason) { setError(reason.message) } finally { setBusy(false) }
  }
  return <Modal title={entry ? `Ubah jurnal ${entry.voucher_no}` : 'Jurnal baru'} onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Batal</Button><Button variant="secondary" disabled={busy} onClick={() => save('DRAFT')}>Simpan Draft</Button><Button disabled={busy || Math.abs(totals.debit - totals.credit) > .001} onClick={() => save('POSTED')}><Send /> Posting Jurnal</Button></>}><div className="grid-equal"><div className="field"><label>NOMOR BUKTI</label><input className="input" placeholder="Otomatis bila kosong" value={form.voucherNo} onChange={(e) => setForm({ ...form, voucherNo: e.target.value })} /></div><div className="field"><label>TANGGAL</label><input className="input" type="date" value={form.entryDate} onChange={(e) => setForm({ ...form, entryDate: e.target.value })} /></div></div><div className="field" style={{ marginTop: 15 }}><label>KETERANGAN</label><input className="input" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Contoh: Pembayaran biaya sewa" /></div><div style={{ marginTop: 19 }} className="journal-lines"><div className="journal-grid header"><span>AKUN</span><span>DEBIT</span><span>KREDIT</span><span /></div>{form.lines.map((line, index) => <div className="journal-grid" key={index}><select className="select" value={line.account_id} onChange={(e) => changeLine(index, 'account_id', e.target.value)}><option value="">Pilih akun</option>{accounts.filter((account) => account.is_active).map((account) => <option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</select><input className="input" min="0" step="0.01" type="number" value={line.debit} onChange={(e) => changeLine(index, 'debit', e.target.value)} /><input className="input" min="0" step="0.01" type="number" value={line.credit} onChange={(e) => changeLine(index, 'credit', e.target.value)} /><button className="icon-button" type="button" disabled={form.lines.length <= 2} onClick={() => setForm({ ...form, lines: form.lines.filter((_, i) => i !== index) })}><X /></button></div>)}</div><div style={{ marginTop: 8 }}><Button variant="secondary" small onClick={() => setForm({ ...form, lines: [...form.lines, { account_id: '', debit: '', credit: '', memo: '' }] })}><Plus /> Tambah baris</Button></div><div className="line-totals"><span className={Math.abs(totals.debit - totals.credit) < .001 ? 'good' : 'bad'}>Debit: {money(totals.debit)}</span><span className={Math.abs(totals.debit - totals.credit) < .001 ? 'good' : 'bad'}>Kredit: {money(totals.credit)}</span></div><ErrorNotice error={error} /></Modal>
}

function Journals({ accounts, notify }) {
  const [range, setRange] = useState({ from: firstDay(), to: today() }); const [modal, setModal] = useState(null)
  const { data, loading, error, reload } = useLoad(() => request(apiPath('/journals', range)), [range.from, range.to])
  async function edit(id) { try { setModal((await request(`/journals/${id}`)).entry) } catch (reason) { notify(reason.message, true) } }
  return <><div className="toolbar"><div><h1 className="page-title">Jurnal umum</h1><p className="page-copy">Catat transaksi dengan sistem debit dan kredit berpasangan.</p></div><Button onClick={() => setModal({})}><Plus /> Jurnal baru</Button></div><div className="panel" style={{ marginBottom: 20 }}><div className="filter-row"><div className="field"><label>DARI</label><input className="input" type="date" value={range.from} onChange={(e) => setRange({ ...range, from: e.target.value })} /></div><div className="field"><label>SAMPAI</label><input className="input" type="date" value={range.to} onChange={(e) => setRange({ ...range, to: e.target.value })} /></div><Button variant="secondary" small onClick={reload}><RefreshCw /> Muat ulang</Button></div></div><ErrorNotice error={error} />{loading ? <PageLoading /> : <section className="panel panel-tight"><div className="table-wrap"><table className="table"><thead><tr><th>Tanggal</th><th>No. Bukti</th><th>Keterangan</th><th>Sumber</th><th>Status</th><th className="number">Nilai</th></tr></thead><tbody>{data?.entries?.map((entry) => <tr key={entry.id} className={entry.status === 'DRAFT' ? 'clickable' : ''} onClick={() => entry.status === 'DRAFT' && edit(entry.id)}><td>{dateLabel(entry.entry_date)}</td><td><strong>{entry.voucher_no}</strong></td><td>{entry.description}</td><td className="muted">{entry.source}</td><td><Badge status={entry.status} /></td><td className="number">{money(entry.total_debit)}</td></tr>)}</tbody></table>{!data?.entries?.length && <Empty>Belum ada jurnal pada rentang tanggal ini.</Empty>}</div></section>}{modal !== null && <JournalModal accounts={accounts} entry={modal.id ? modal : null} onClose={() => setModal(null)} onSaved={() => { setModal(null); reload() }} notify={notify} />}</>
}

function ImportExcel({ notify }) {
  const [file, setFile] = useState(null); const [preview, setPreview] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function previewFile() { if (!file) return; setBusy(true); setError(''); try { const form = new FormData(); form.append('file', file); setPreview(await request('/imports/preview', { method: 'POST', body: form })) } catch (reason) { setError(reason.message) } finally { setBusy(false) } }
  async function confirm() { setBusy(true); try { const result = await request(`/imports/${preview.batchId}/confirm`, { method: 'POST' }); notify(`${result.posted} jurnal berhasil diposting dari Excel.`); setPreview(null); setFile(null) } catch (reason) { setError(reason.message) } finally { setBusy(false) } }
  return <><div className="toolbar"><div><h1 className="page-title">Impor jurnal Excel</h1><p className="page-copy">Validasi dulu, lalu posting seluruh transaksi dalam satu proses aman.</p></div><Button variant="secondary" onClick={() => download('/imports/template', 'template-jurnal-finova.xlsx')}><Download /> Template Excel</Button></div><div className="grid-two"><section className="panel"><h3 className="panel-title">Unggah template jurnal</h3><p className="panel-subtitle">Kolom wajib: Tanggal, NoBukti, Keterangan, KodeAkun, Debit, dan Kredit.</p><label className="upload-zone"><Upload /><strong>{file ? file.name : 'Pilih berkas .xlsx'}</strong><span>Ukuran maksimal 10 MB. Satu NoBukti membentuk satu jurnal berpasangan.</span><input type="file" accept=".xlsx,.xls" onChange={(event) => { setFile(event.target.files?.[0] || null); setPreview(null); setError('') }} /></label><div style={{ marginTop: 15 }}><Button disabled={!file || busy} onClick={previewFile}><FileSpreadsheet /> {busy ? 'Memvalidasi…' : 'Pratinjau & validasi'}</Button></div><ErrorNotice error={error} /></section><section className="panel"><h3 className="panel-title">Proses otomatis</h3><p className="panel-subtitle">Finova melakukan pemeriksaan berikut sebelum transaksi masuk laporan.</p><div className="report-line"><span>Format dan tanggal transaksi</span><CheckCircle2 className="good" size={17} /></div><div className="report-line"><span>Kode akun aktif</span><CheckCircle2 className="good" size={17} /></div><div className="report-line"><span>Keseimbangan debit dan kredit</span><CheckCircle2 className="good" size={17} /></div><div className="report-line"><span>Periode terbuka dan nomor bukti unik</span><CheckCircle2 className="good" size={17} /></div></section></div>{preview && <section className="panel" style={{ marginTop: 20 }}><div className="split-head"><div><h3 className="panel-title">Hasil validasi</h3><p className="panel-subtitle">{preview.totalRows} baris menghasilkan {preview.entries.length} jurnal.</p></div>{preview.valid ? <Button disabled={busy} onClick={confirm}><CheckCircle2 /> Konfirmasi & posting</Button> : <Badge status="REJECTED" />}</div>{preview.valid ? <div className="success-box">Semua transaksi valid. Konfirmasi akan memposting seluruh batch sekaligus.</div> : <div className="error-box"><strong>Perbaiki berkas sebelum diposting.</strong>{preview.errors.map((item, index) => <div key={index}>Baris {item.line || '—'}: {item.message}</div>)}</div>}<div className="table-wrap" style={{ marginTop: 15 }}><table className="table"><thead><tr><th>No. Bukti</th><th>Tanggal</th><th>Keterangan</th><th className="number">Baris</th></tr></thead><tbody>{preview.entries.map((entry) => <tr key={entry.voucherNo}><td>{entry.voucherNo}</td><td>{dateLabel(entry.entryDate)}</td><td>{entry.description}</td><td className="number">{entry.lineCount}</td></tr>)}</tbody></table></div></section>}</>
}

function AccountModal({ account, onClose, onSaved, notify }) {
  const defaults = account || { code: '', name: '', account_group: 'ASSET', account_subtype: '', normal_balance: 'DEBIT', cash_flow_category: 'OPERATING', is_cash_account: false, is_active: true }
  const [form, setForm] = useState({ ...defaults }); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  function setGroup(group) { setForm({ ...form, account_group: group, normal_balance: ['ASSET', 'EXPENSE'].includes(group) ? 'DEBIT' : 'CREDIT' }) }
  async function save() { setBusy(true); setError(''); try { const body = account ? { name: form.name, accountSubtype: form.account_subtype || null, cashFlowCategory: form.cash_flow_category, isCashAccount: form.is_cash_account, isActive: form.is_active } : { code: form.code, name: form.name, accountGroup: form.account_group, accountSubtype: form.account_subtype || null, normalBalance: form.normal_balance, cashFlowCategory: form.cash_flow_category, isCashAccount: form.is_cash_account }; await request(account ? `/accounts/${account.id}` : '/accounts', { method: account ? 'PUT' : 'POST', body }); notify(`Akun berhasil ${account ? 'diperbarui' : 'ditambahkan'}.`); onSaved() } catch (reason) { setError(reason.message) } finally { setBusy(false) } }
  return <Modal title={account ? `Ubah akun ${account.code}` : 'Tambah akun'} onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Batal</Button><Button disabled={busy} onClick={save}>Simpan akun</Button></>}><div className="grid-equal"><div className="field"><label>KODE AKUN</label><input className="input" disabled={Boolean(account)} value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /></div><div className="field"><label>KELOMPOK</label><select className="select" disabled={Boolean(account)} value={form.account_group} onChange={(e) => setGroup(e.target.value)}>{['ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE'].map((item) => <option key={item}>{item}</option>)}</select></div></div><div className="field" style={{ marginTop: 14 }}><label>NAMA AKUN</label><input className="input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div className="grid-equal" style={{ marginTop: 14 }}><div className="field"><label>SUBTIPE</label><input className="input" placeholder="Contoh: RECEIVABLE" value={form.account_subtype || ''} onChange={(e) => setForm({ ...form, account_subtype: e.target.value })} /></div><div className="field"><label>ARUS KAS</label><select className="select" value={form.cash_flow_category} onChange={(e) => setForm({ ...form, cash_flow_category: e.target.value })}>{['OPERATING', 'INVESTING', 'FINANCING'].map((item) => <option key={item}>{item}</option>)}</select></div></div><div style={{ display: 'flex', gap: 22, marginTop: 18, fontSize: 13 }}><label><input type="checkbox" checked={Boolean(form.is_cash_account)} onChange={(e) => setForm({ ...form, is_cash_account: e.target.checked })} /> Akun kas/bank</label>{account && <label><input type="checkbox" checked={Boolean(form.is_active)} onChange={(e) => setForm({ ...form, is_active: e.target.checked })} /> Akun aktif</label>}</div><ErrorNotice error={error} /></Modal>
}

function Accounts({ user, notify }) {
  const { data, loading, error, reload } = useLoad(() => request('/accounts'), [])
  const [modal, setModal] = useState(null)
  return <><div className="toolbar"><div><h1 className="page-title">Chart of Accounts</h1><p className="page-copy">Kode akun adalah fondasi otomatisasi laporan keuangan Anda.</p></div>{user.role === 'ADMIN' && <Button onClick={() => setModal({})}><Plus /> Tambah akun</Button>}</div><ErrorNotice error={error} />{loading ? <PageLoading /> : <section className="panel panel-tight"><div className="table-wrap"><table className="table"><thead><tr><th>Kode</th><th>Nama akun</th><th>Kelompok</th><th>Saldo normal</th><th>Arus kas</th><th>Status</th></tr></thead><tbody>{data?.accounts?.map((account) => <tr key={account.id} className={user.role === 'ADMIN' ? 'clickable' : ''} onClick={() => user.role === 'ADMIN' && setModal(account)}><td><strong>{account.code}</strong></td><td>{account.name}{account.is_cash_account ? <span className="badge green" style={{ marginLeft: 8 }}>KAS/BANK</span> : null}</td><td>{account.account_group}</td><td>{account.normal_balance}</td><td>{account.cash_flow_category}</td><td><Badge status={account.is_active ? 'OPEN' : 'CLOSED'} /></td></tr>)}</tbody></table></div></section>}{modal !== null && <AccountModal account={modal.id ? modal : null} onClose={() => setModal(null)} onSaved={() => { setModal(null); reload() }} notify={notify} />}</>
}

function PeriodModal({ onClose, onSaved, notify }) {
  const [form, setForm] = useState({ name: '', startDate: firstDay(), endDate: today() }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function save() { setBusy(true); try { await request('/periods', { method: 'POST', body: form }); notify('Periode akuntansi ditambahkan.'); onSaved() } catch (reason) { setError(reason.message) } finally { setBusy(false) } }
  return <Modal title="Tambah periode" onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Batal</Button><Button disabled={busy} onClick={save}>Simpan periode</Button></>}><div className="field"><label>NAMA PERIODE</label><input className="input" placeholder="Contoh: Januari 2026" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div className="grid-equal" style={{ marginTop: 14 }}><div className="field"><label>TANGGAL MULAI</label><input className="input" type="date" value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })} /></div><div className="field"><label>TANGGAL SELESAI</label><input className="input" type="date" value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} /></div></div><ErrorNotice error={error} /></Modal>
}

function Periods({ notify }) {
  const { data, loading, error, reload } = useLoad(() => request('/periods'), []); const [showForm, setShowForm] = useState(false); const [closing, setClosing] = useState(null)
  async function close(period) { if (!window.confirm(`Tutup dan kunci periode ${period.name}? Jurnal yang sudah terposting tidak dapat diubah.`)) return; setClosing(period.id); try { const result = await request(`/periods/${period.id}/close`, { method: 'POST' }); notify(`Periode ditutup. Laba bersih: ${money(result.netIncome)}.`); reload() } catch (reason) { notify(reason.message, true) } finally { setClosing(null) } }
  return <><div className="toolbar"><div><h1 className="page-title">Periode akuntansi</h1><p className="page-copy">Tutup bulan setelah laporan ditinjau untuk mengunci pembukuan.</p></div><Button onClick={() => setShowForm(true)}><Plus /> Tambah periode</Button></div><ErrorNotice error={error} />{loading ? <PageLoading /> : <section className="panel panel-tight"><div className="table-wrap"><table className="table"><thead><tr><th>Periode</th><th>Mulai</th><th>Selesai</th><th>Status</th><th /></tr></thead><tbody>{data?.periods?.map((period) => <tr key={period.id}><td><strong>{period.name}</strong></td><td>{dateLabel(period.start_date)}</td><td>{dateLabel(period.end_date)}</td><td><Badge status={period.status} /></td><td className="number">{period.status === 'OPEN' && <Button small variant="secondary" disabled={closing === period.id} onClick={() => close(period)}><LockKeyhole /> Tutup buku</Button>}</td></tr>)}</tbody></table></div></section>}{showForm && <PeriodModal onClose={() => setShowForm(false)} onSaved={() => { setShowForm(false); reload() }} notify={notify} />}</>
}

function UserModal({ onClose, onSaved, notify }) {
  const [form, setForm] = useState({ name: '', email: '', password: '', role: 'STAFF' }); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function save() { setBusy(true); try { await request('/users', { method: 'POST', body: form }); notify('Pengguna baru berhasil dibuat.'); onSaved() } catch (reason) { setError(reason.message) } finally { setBusy(false) } }
  return <Modal title="Tambah pengguna" onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Batal</Button><Button disabled={busy} onClick={save}>Buat pengguna</Button></>}><div className="field"><label>NAMA</label><input className="input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div className="field" style={{ marginTop: 14 }}><label>EMAIL</label><input className="input" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></div><div className="grid-equal" style={{ marginTop: 14 }}><div className="field"><label>KATA SANDI AWAL</label><input className="input" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></div><div className="field"><label>PERAN</label><select className="select" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="STAFF">Staf keuangan</option><option value="ADMIN">Administrator</option></select></div></div><ErrorNotice error={error} /></Modal>
}

function UsersPage({ notify, currentUser }) {
  const { data, loading, error, reload } = useLoad(() => request('/users'), []); const [modal, setModal] = useState(false)
  async function toggle(item) { try { await request(`/users/${item.id}`, { method: 'PATCH', body: { isActive: !item.isActive } }); notify(`Pengguna ${item.isActive ? 'dinonaktifkan' : 'diaktifkan'}.`); reload() } catch (reason) { notify(reason.message, true) } }
  return <><div className="toolbar"><div><h1 className="page-title">Pengguna</h1><p className="page-copy">Atur siapa yang mencatat transaksi dan mengelola pembukuan.</p></div><Button onClick={() => setModal(true)}><Plus /> Tambah pengguna</Button></div><ErrorNotice error={error} />{loading ? <PageLoading /> : <section className="panel panel-tight"><div className="table-wrap"><table className="table"><thead><tr><th>Nama</th><th>Email</th><th>Peran</th><th>Status</th><th /></tr></thead><tbody>{data?.users?.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.email}</td><td><Badge status={item.role} /></td><td><Badge status={item.isActive ? 'OPEN' : 'CLOSED'} /></td><td className="number">{item.id !== currentUser.id && <Button small variant="secondary" onClick={() => toggle(item)}>{item.isActive ? 'Nonaktifkan' : 'Aktifkan'}</Button>}</td></tr>)}</tbody></table></div></section>}{modal && <UserModal onClose={() => setModal(false)} onSaved={() => { setModal(false); reload() }} notify={notify} />}</>
}

function SettingsPage({ company, onUpdated, notify }) {
  const [form, setForm] = useState(() => ({ name: company?.name || '', address: company?.address || '', phone: company?.phone || '', email: company?.email || '', fiscalYearStart: company?.fiscal_year_start || 1 })); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => setForm({ name: company?.name || '', address: company?.address || '', phone: company?.phone || '', email: company?.email || '', fiscalYearStart: company?.fiscal_year_start || 1 }), [company])
  async function save(event) { event.preventDefault(); setBusy(true); try { await request('/company', { method: 'PUT', body: form }); notify('Profil perusahaan disimpan.'); onUpdated() } catch (reason) { setError(reason.message) } finally { setBusy(false) } }
  return <><h1 className="page-title">Pengaturan perusahaan</h1><p className="page-copy">Informasi ini akan muncul pada setiap laporan yang diekspor.</p><form className="panel" onSubmit={save} style={{ maxWidth: 760 }}><div className="field"><label>NAMA PERUSAHAAN</label><input className="input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></div><div className="field" style={{ marginTop: 14 }}><label>ALAMAT</label><textarea className="textarea" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /></div><div className="grid-equal" style={{ marginTop: 14 }}><div className="field"><label>TELEPON</label><input className="input" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></div><div className="field"><label>EMAIL</label><input className="input" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></div></div><div className="field" style={{ marginTop: 14, maxWidth: 230 }}><label>BULAN AWAL TAHUN BUKU</label><select className="select" value={form.fiscalYearStart} onChange={(e) => setForm({ ...form, fiscalYearStart: Number(e.target.value) })}>{Array.from({ length: 12 }, (_, i) => <option key={i + 1} value={i + 1}>{new Intl.DateTimeFormat('id-ID', { month: 'long' }).format(new Date(2026, i, 1))}</option>)}</select></div><ErrorNotice error={error} /><div style={{ marginTop: 20 }}><Button disabled={busy}>{busy ? 'Menyimpan…' : 'Simpan pengaturan'}</Button></div></form></>
}

const reportOptions = [
  ['journal', 'Jurnal Umum'], ['ledger', 'Buku Besar'], ['trial-balance', 'Neraca Saldo'], ['income-statement', 'Laba Rugi'], ['balance-sheet', 'Neraca Posisi Keuangan'], ['equity-changes', 'Perubahan Modal'], ['cash-flow', 'Arus Kas']
]

function reportExportRows(kind, data) {
  if (!data) return { headers: [], rows: [] }
  if (kind === 'journal') return { headers: ['Tanggal', 'No. Bukti', 'Keterangan', 'Akun', 'Debit', 'Kredit'], rows: data.flatMap((entry) => entry.lines.map((line) => [entry.entry_date, entry.voucher_no, entry.description, `${line.code} — ${line.account_name}`, line.debit, line.credit])) }
  if (kind === 'ledger') return { headers: ['Tanggal', 'No. Bukti', 'Keterangan', 'Debit', 'Kredit', 'Saldo'], rows: data.rows.map((line) => [line.entry_date, line.voucher_no, line.description, line.debit, line.credit, line.balance]) }
  if (kind === 'trial-balance') return { headers: ['Kode', 'Nama Akun', 'Debit', 'Kredit'], rows: data.rows.map((row) => [row.code, row.name, row.debit, row.credit]) }
  if (kind === 'income-statement') return { headers: ['Kelompok', 'Kode', 'Akun', 'Nominal'], rows: [...data.revenue.map((row) => ['Pendapatan', row.code, row.name, row.amount]), ...data.expenses.map((row) => ['Beban', row.code, row.name, row.amount]), ['Laba Bersih', '', '', data.netIncome]] }
  if (kind === 'balance-sheet') return { headers: ['Kelompok', 'Kode', 'Akun', 'Nominal'], rows: [...data.assets.rows.map((row) => ['Aktiva', row.code, row.name, row.amount]), ...data.liabilities.rows.map((row) => ['Liabilitas', row.code, row.name, row.amount]), ...data.equity.rows.map((row) => ['Ekuitas', row.code, row.name, row.amount]), ['Ekuitas', '', 'Laba periode berjalan', data.equity.unclosedProfit]] }
  if (kind === 'equity-changes') return { headers: ['Keterangan', 'Nominal'], rows: [['Modal awal', data.opening], ['Tambahan modal', data.capital], ['Prive', data.drawings], ['Laba bersih', data.netIncome], ['Modal akhir', data.closing]] }
  return { headers: ['Keterangan', 'Nominal'], rows: [['Arus kas operasi', data.operating], ['Arus kas investasi', data.investing], ['Arus kas pendanaan', data.financing], ['Kenaikan/(penurunan) kas', data.netChange]] }
}

function exportReport(kind, label, response, type) {
  const { headers, rows } = reportExportRows(kind, response.data)
  const dateRange = `${response.period.from} s.d. ${response.period.to}`
  if (type === 'xlsx') {
    const sheet = XLSX.utils.aoa_to_sheet([[response.company.name], [label], [`Periode: ${dateRange}`], [], headers, ...rows])
    sheet['!cols'] = headers.map((header, index) => ({ wch: Math.max(header.length + 3, ...rows.map((row) => String(row[index] ?? '').length + 2), 15) }))
    const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, sheet, 'Laporan'); XLSX.writeFile(workbook, `${kind}-${response.period.to}.xlsx`)
  } else {
    const doc = new jsPDF(); doc.setFontSize(16); doc.text(response.company.name, 14, 16); doc.setFontSize(12); doc.text(label, 14, 24); doc.setFontSize(9); doc.text(`Periode: ${dateRange} · Dicetak ${dateLabel(today())}`, 14, 30)
    autoTable(doc, { startY: 36, head: [headers], body: rows.map((row) => row.map((value, index) => index >= headers.length - 2 && typeof value === 'number' ? number(value) : String(value ?? ''))), styles: { fontSize: 8 }, headStyles: { fillColor: [14, 113, 69] } })
    doc.save(`${kind}-${response.period.to}.pdf`)
  }
}

function ReportDocument({ kind, report }) {
  const data = report?.data
  if (!data) return <Empty>Pilih laporan dan periode untuk memulai.</Empty>
  const Section = ({ title, rows, total, label = 'Total' }) => <><div className="report-section">{title}</div>{rows.map((row) => <div className="report-line indent" key={`${title}${row.code}${row.name}`}><span>{row.code ? `${row.code} — ${row.name}` : row.name}</span><span>{money(row.amount)}</span></div>)}<div className="report-line total"><span>{label}</span><span>{money(total)}</span></div></>
  if (kind === 'journal') return <div className="table-wrap"><table className="table"><thead><tr><th>Tanggal</th><th>No. Bukti</th><th>Keterangan / Akun</th><th className="number">Debit</th><th className="number">Kredit</th></tr></thead><tbody>{data.flatMap((entry) => entry.lines.map((line, index) => <tr key={`${entry.id}-${line.account_id}`}><td>{index === 0 ? dateLabel(entry.entry_date) : ''}</td><td>{index === 0 ? entry.voucher_no : ''}</td><td>{index === 0 && <span className="muted">{entry.description}<br /></span>}<span style={{ paddingLeft: 12 }}>{line.code} — {line.account_name}</span></td><td className="number">{line.debit ? money(line.debit) : ''}</td><td className="number">{line.credit ? money(line.credit) : ''}</td></tr>))}</tbody></table>{!data.length && <Empty>Belum ada jurnal terposting pada periode ini.</Empty>}</div>
  if (kind === 'ledger') return <><div className="report-line total"><span>Saldo awal — {data.account.code} {data.account.name}</span><span>{money(data.opening)}</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Tanggal</th><th>No. Bukti</th><th>Keterangan</th><th className="number">Debit</th><th className="number">Kredit</th><th className="number">Saldo</th></tr></thead><tbody>{data.rows.map((row, index) => <tr key={index}><td>{dateLabel(row.entry_date)}</td><td>{row.voucher_no}</td><td>{row.description}</td><td className="number">{row.debit ? money(row.debit) : ''}</td><td className="number">{row.credit ? money(row.credit) : ''}</td><td className="number"><strong>{money(row.balance)}</strong></td></tr>)}<tr className="total-row"><td colSpan="5">Saldo akhir</td><td className="number">{money(data.closing)}</td></tr></tbody></table></div></>
  if (kind === 'trial-balance') return <div className="table-wrap"><table className="table"><thead><tr><th>Kode</th><th>Nama akun</th><th className="number">Debit</th><th className="number">Kredit</th></tr></thead><tbody>{data.rows.map((row) => <tr key={row.accountId}><td>{row.code}</td><td>{row.name}</td><td className="number">{row.debit ? money(row.debit) : ''}</td><td className="number">{row.credit ? money(row.credit) : ''}</td></tr>)}<tr className="total-row"><td colSpan="2">Total</td><td className="number">{money(data.totals.debit)}</td><td className="number">{money(data.totals.credit)}</td></tr></tbody></table></div>
  if (kind === 'income-statement') return <><Section title="Pendapatan" rows={data.revenue} total={data.revenueTotal} label="Total pendapatan" /><Section title="Beban" rows={data.expenses} total={data.expenseTotal} label="Total beban" /><div className="report-line grand"><span>Laba bersih periode berjalan</span><span>{money(data.netIncome)}</span></div></>
  if (kind === 'balance-sheet') return <><Section title="Aktiva" rows={data.assets.rows} total={data.assets.total} label="Total aktiva" /><Section title="Liabilitas" rows={data.liabilities.rows} total={data.liabilities.total} label="Total liabilitas" /><Section title="Ekuitas" rows={[...data.equity.rows, { name: 'Laba periode berjalan', amount: data.equity.unclosedProfit }]} total={data.equity.total} label="Total ekuitas" /><div className={`report-line grand ${data.balanced ? '' : 'bad'}`}><span>Liabilitas + Ekuitas</span><span>{money(data.liabilities.total + data.equity.total)}</span></div></>
  if (kind === 'equity-changes') return <><div className="report-line"><span>Modal awal</span><span>{money(data.opening)}</span></div><div className="report-line"><span>Tambahan modal pemilik</span><span>{money(data.capital)}</span></div><div className="report-line"><span>Prive</span><span>{money(data.drawings)}</span></div><div className="report-line"><span>Laba bersih</span><span>{money(data.netIncome)}</span></div><div className="report-line grand"><span>Modal akhir</span><span>{money(data.closing)}</span></div></>
  return <><div className="report-line"><span>Arus kas dari aktivitas operasi</span><span>{money(data.operating)}</span></div><div className="report-line"><span>Arus kas dari aktivitas investasi</span><span>{money(data.investing)}</span></div><div className="report-line"><span>Arus kas dari aktivitas pendanaan</span><span>{money(data.financing)}</span></div><div className="report-line grand"><span>Kenaikan/(penurunan) kas</span><span>{money(data.netChange)}</span></div></>
}

function Reports({ accounts, notify }) {
  const [kind, setKind] = useState('income-statement'); const [range, setRange] = useState({ from: firstDay(), to: today() }); const [accountId, setAccountId] = useState('')
  const query = useMemo(() => ({ ...range, accountId: kind === 'ledger' ? accountId : undefined }), [kind, range, accountId])
  const { data, loading, error, reload } = useLoad(() => kind === 'ledger' && !accountId ? Promise.resolve(null) : request(apiPath(`/reports/${kind}`, query)), [kind, range.from, range.to, accountId])
  const selectedLabel = reportOptions.find(([key]) => key === kind)?.[1]
  function exportFile(type) { try { if (!data) return; exportReport(kind, selectedLabel, data, type); notify(`Laporan diekspor ke ${type.toUpperCase()}.`) } catch (reason) { notify(reason.message, true) } }
  return <><div className="toolbar"><div><h1 className="page-title">Laporan keuangan</h1><p className="page-copy">Semua angka dihitung dari jurnal terposting pada periode yang Anda pilih.</p></div><div style={{ display: 'flex', gap: 8 }}><Button variant="secondary" disabled={!data} onClick={() => exportFile('xlsx')}><FileSpreadsheet /> Excel</Button><Button variant="secondary" disabled={!data} onClick={() => exportFile('pdf')}><Download /> PDF</Button></div></div><section className="panel" style={{ marginBottom: 20 }}><div className="filter-row"><div className="field" style={{ minWidth: 220 }}><label>JENIS LAPORAN</label><select className="select" value={kind} onChange={(e) => setKind(e.target.value)}>{reportOptions.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div>{kind === 'ledger' && <div className="field" style={{ minWidth: 220 }}><label>AKUN</label><select className="select" value={accountId} onChange={(e) => setAccountId(e.target.value)}><option value="">Pilih akun</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</select></div>}<div className="field"><label>DARI</label><input className="input" type="date" value={range.from} onChange={(e) => setRange({ ...range, from: e.target.value })} /></div><div className="field"><label>SAMPAI</label><input className="input" type="date" value={range.to} onChange={(e) => setRange({ ...range, to: e.target.value })} /></div><Button small variant="secondary" onClick={reload}><RefreshCw /> Terapkan</Button></div></section><ErrorNotice error={error} />{loading ? <PageLoading /> : <section className="panel panel-tight"><div className="report-heading"><div className="muted">{data?.company?.name || 'Perusahaan Anda'}</div><h2>{selectedLabel}</h2><p>Periode {dateLabel(range.from)} — {dateLabel(range.to)}</p></div><ReportDocument kind={kind} report={data} /></section>}</>
}

function Workspace({ user, onLogout }) {
  const [route, setRoute] = useState('dashboard'); const [toast, setToast] = useState(null)
  const companyState = useLoad(() => request('/company'), []); const accountsState = useLoad(() => request('/accounts'), [])
  const notify = useCallback((message, error = false) => { setToast({ message, error }); window.setTimeout(() => setToast(null), 3600) }, [])
  if (companyState.loading || accountsState.loading) return <PageLoading />
  const company = companyState.data?.company; const accounts = accountsState.data?.accounts || []
  const page = route === 'dashboard' ? <Dashboard /> : route === 'journals' ? <Journals accounts={accounts} notify={notify} /> : route === 'imports' ? <ImportExcel notify={notify} /> : route === 'reports' ? <Reports accounts={accounts} notify={notify} /> : route === 'accounts' ? <Accounts user={user} notify={notify} /> : route === 'periods' ? <Periods notify={notify} /> : route === 'users' ? <UsersPage currentUser={user} notify={notify} /> : <SettingsPage company={company} notify={notify} onUpdated={companyState.reload} />
  return <AppShell user={user} company={company} route={route} setRoute={setRoute} onLogout={onLogout}>{companyState.error || accountsState.error ? <ErrorNotice error={companyState.error || accountsState.error} /> : page}{toast && <div className={`toast ${toast.error ? 'error' : ''}`}>{toast.message}</div>}</AppShell>
}

export default function App() {
  const [session, setSession] = useState({ loading: true, user: null })
  useEffect(() => { request('/auth/me').then((data) => setSession({ loading: false, user: data.user })).catch(() => setSession({ loading: false, user: null })) }, [])
  async function logout() { try { await request('/auth/logout', { method: 'POST' }) } finally { setSession({ loading: false, user: null }) } }
  if (session.loading) return <PageLoading />
  return session.user ? <Workspace user={session.user} onLogout={logout} /> : <Login onLogin={(user) => setSession({ loading: false, user })} />
}
